<a href="https://colab.research.google.com/github/kunal077/Stochastic_Processes_Algorithms/blob/main/MarkovChain_FundamentalMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MARKOV CHAIN CLASS

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

class MarkovChain():
  def __init__(self, transition_prob):
    self.transition_prob = transition_prob
    self.states= list(transition_prob.keys())

    def next_state(self, current_state):
      return np.random.choice(
          self.states, p = [self.transition_prob[current_state][next_state]
                            for next_state in self.states])
      
      def generate_states(self, current_state, no ):
        future_states = []
        for i in range(no):
          future_states.append(self.next_state(current_state))
        return future_states

TRANSITION PROBABILITY MATRIX

In [ ]:
transition_prob = {'X0':{'X0':1, 'X1':0, 'X2':0, 'X3':0, 'X4':0},
                  'X1':{'X0':0.6, 'X1':0, 'X2':0.4, 'X3':0, 'X4':0},
                  'X2':{'X0':0, 'X1':0.6, 'X2':0, 'X3':0.4, 'X4':0},
                  'X3':{'X0':0, 'X1':0, 'X2':0.6, 'X3':0, 'X4':0.4},
                  'X4':{'X0':0, 'X1':0, 'X2':0, 'X3':0, 'X4':1}}


gambler_chain = MarkovChain(transition_prob=transition_prob)
absorbing_states = 2
total_states = 5
non_absorbing_states = total_states - absorbing_states

CONVERTING DICTIONARY TO PROBABILITY TRANSITION MATRIX

In [ ]:
final_list = []
for name in gambler_chain.transition_prob:
  temp_list = []
  print(name, gambler_chain.transition_prob[name])
  print(gambler_chain.transition_prob[name].keys(), gambler_chain.transition_prob[name].values())
  temp_list.append(list(gambler_chain.transition_prob[name].values()))
  final_list.append(temp_list)

print()
print(final_list)
print()
return_matrix = [[0 for x in range(total_states)]for y in range(total_states)]
print(return_matrix)
i, j = 0, 0
new_final_list = []
for namekey in final_list:
  new_temp_list = []
  for keyvalue in namekey[0]:
    new_temp_list.append(keyvalue)
  new_final_list.append(new_temp_list)

print()
print(new_final_list[:][:])
final_return_matrix = new_final_list
print(final_return_matrix)

X0 {'X0': 1, 'X1': 0, 'X2': 0, 'X3': 0, 'X4': 0}
dict_keys(['X0', 'X1', 'X2', 'X3', 'X4']) dict_values([1, 0, 0, 0, 0])
X1 {'X0': 0.6, 'X1': 0, 'X2': 0.4, 'X3': 0, 'X4': 0}
dict_keys(['X0', 'X1', 'X2', 'X3', 'X4']) dict_values([0.6, 0, 0.4, 0, 0])
X2 {'X0': 0, 'X1': 0.6, 'X2': 0, 'X3': 0.4, 'X4': 0}
dict_keys(['X0', 'X1', 'X2', 'X3', 'X4']) dict_values([0, 0.6, 0, 0.4, 0])
X3 {'X0': 0, 'X1': 0, 'X2': 0.6, 'X3': 0, 'X4': 0.4}
dict_keys(['X0', 'X1', 'X2', 'X3', 'X4']) dict_values([0, 0, 0.6, 0, 0.4])
X4 {'X0': 0, 'X1': 0, 'X2': 0, 'X3': 0, 'X4': 1}
dict_keys(['X0', 'X1', 'X2', 'X3', 'X4']) dict_values([0, 0, 0, 0, 1])

[[[1, 0, 0, 0, 0]], [[0.6, 0, 0.4, 0, 0]], [[0, 0.6, 0, 0.4, 0]], [[0, 0, 0.6, 0, 0.4]], [[0, 0, 0, 0, 1]]]

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

[[1, 0, 0, 0, 0], [0.6, 0, 0.4, 0, 0], [0, 0.6, 0, 0.4, 0], [0, 0, 0.6, 0, 0.4], [0, 0, 0, 0, 1]]
[[1, 0, 0, 0, 0], [0.6, 0, 0.4, 0, 0], [0, 0.6, 0, 0.4, 0], [0, 0, 0.6, 0, 0.4], 

CONVERTING MATRIX TO Q,R,0,I MATRIX FROM PROBABILITY TRANSITION MATRIX

temp = []
temp = final_return_matrix[:][0]
for i in range(3):
  final_return_matrix[:][i] = final_return_matrix[:][i+1]
final_return_matrix[:][3] = temp

temp = final_return_matrix[0][:]
for i in range(3):
  final_return_matrix[i][:] = final_return_matrix[i+1][:]
final_return_matrix[3][:] = temp

I MATRIX (consisting of absorbing states)

In [ ]:
#constructing I for absorbing states
Imatrix = [[0 for i in range(3)] for j in range(3)]
for i in range(3):
  Imatrix[i][i] = 1

print(Imatrix)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


Q MATRIX (consisting of non-absorbing to non-absorbing states)

In [ ]:
Qmatrix = []
for i in range(1,4):
  coloumn_temp_list = []
  for j in range(1,4):
    coloumn_temp_list.append(final_return_matrix[i][j])
  Qmatrix.append(coloumn_temp_list)
print("Q MATRIX\n")
print(Qmatrix)

Q MATRIX

[[0, 0.4, 0], [0.6, 0, 0.4], [0, 0.6, 0]]


R MATRIX (consisting of non-absorbing to absorbing states)

In [ ]:
Rmatrix = []
for i in range(5):
  coloumn_temp_list_rmatrix = []
  for j in range(5):
    if((i== 1 or i== 2 or i== 3)and(j == 0 or j == 4)):
      coloumn_temp_list_rmatrix.append(final_return_matrix[i][j])
  Rmatrix.append(coloumn_temp_list_rmatrix)
print(Rmatrix)

newRmatrix = []
for row in Rmatrix:
  if row != []:
    newRmatrix.append(row)
print(newRmatrix)

del Rmatrix
Rmatrix = []
Rmatrix = newRmatrix

[[], [0.6, 0], [0, 0], [0, 0.4], []]
[[0.6, 0], [0, 0], [0, 0.4]]


In [ ]:
print(Imatrix)
print()
print(Qmatrix)
print()
print(Rmatrix)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

[[0, 0.4, 0], [0.6, 0, 0.4], [0, 0.6, 0]]

[[0.6, 0], [0, 0], [0, 0.4]]


Now using fundamental matrix we can find (a) The expected number of periods spent in state Tj starting from state Ti will be the i,j the element of Fundamental Matrix and (b) Probability that it will be eventually be absorbed in state Tj starting from state Ti

In [ ]:
temp_fundamental_matrix = [[0 for x in range(3)]for y in range(3)]
for i in range(3):
  for j in range(3):
    temp_fundamental_matrix[i][j] = Imatrix[i][j] - Qmatrix[i][j]

import numpy as np
temp_fundamental_matrix = np.array(temp_fundamental_matrix)
fundamental_matrix = np.linalg.inv(temp_fundamental_matrix)
print("\nFUNDAMENTAL MATRIX WILL BE")
print(fundamental_matrix)
print()
for i in range(3):
  for j in range(3):
    print("Expected number of periods that it will spend in "+str(j)+" starting from "+ str(i)+ " :- ", fundamental_matrix[i][j])

print()
print()
absorbtion_matrix = np.dot(fundamental_matrix, Rmatrix)
#print(absorbtion_matrix)
for i in range(3):
  for j in range(2):
    print("Probability of absorbtion in state "+ str(j)+ " starting at "+str(i)+" :- ", absorbtion_matrix[i][j])



FUNDAMENTAL MATRIX WILL BE
[[1.46153846 0.76923077 0.30769231]
 [1.15384615 1.92307692 0.76923077]
 [0.69230769 1.15384615 1.46153846]]

Expected number of periods that it will spend in 0 starting from 0 :-  1.4615384615384617
Expected number of periods that it will spend in 1 starting from 0 :-  0.7692307692307694
Expected number of periods that it will spend in 2 starting from 0 :-  0.3076923076923077
Expected number of periods that it will spend in 0 starting from 1 :-  1.153846153846154
Expected number of periods that it will spend in 1 starting from 1 :-  1.9230769230769234
Expected number of periods that it will spend in 2 starting from 1 :-  0.7692307692307693
Expected number of periods that it will spend in 0 starting from 2 :-  0.6923076923076923
Expected number of periods that it will spend in 1 starting from 2 :-  1.153846153846154
Expected number of periods that it will spend in 2 starting from 2 :-  1.4615384615384617


Probability of absorbtion in state 0 starting at 0 :